### PR TITLE
Revises the SQL to support PostgreSQL.

### PR DESCRIPTION
**Pull request by msolnit**
## Describe your changes
PostgreSQL compatibility for the models and macros in this repo. Specifically:

- New `postgresql` variants of the adapter-based macros.
- Change a few hard-coded SQL expressions to use the built-in dbt compatibility equivalents.

## How has this been tested?
I ran `dbt build --full-refresh` and all tests passed. I *only* ran it with PostgreSQL, and did *not* try Redshift, BigQuery or Snowflake.

## Checklist before requesting a review
- [ ]  (Optional) I have recorded a Loom performing a self-review of my code
- [ ]  My code follows style guidelines
- [ ]  I have commented my code as necessary
- [ ]  (New models only) I have implemented generic dbt tests to validate primary keys/uniqueness in my model
- [ ]  I have added at least one Github label to this PR

### CODE REVIEW

**Comment by msolnit** [comment]
Comments:

- If someone else could try this with the officially-supported warehouses, I'd appreciate it.
- I suspect that the `try_to_cast_date` changes are **also** needed for Redshift, and that the current Redshift implementation is broken. Specifically, I don't think Redshift supports `\d` for the `SIMILAR TO` operator.
- This PR does **not** include changes that are needed in **other** Tuva repos for full end-to-end PostgreSQL compatibility. If there's appetite, then I can submit PRs for those too.

**Comment by thutuva** [comment]
Hi @msolnit - Thank you for submitting this PR.  I previously commented on the PR you submitted to the_tuva-project and wanted to acknowledge this PR is being looked at as well.  I will update you once I've reviewed and tested this PR.   Cheers!

**Comment by sarah-tuva** [comment]
Local CI testing passed. Results:

Screenshot 2023-06-07 at 3 46 19 PM

Screenshot 2023-06-07 at 4 49 01 PM

Screenshot 2023-06-07 at 3 55 14 PM

**Comment by sarah-tuva** [comment]
Hey @msolnit, thank you so much for your contributions. One thing that came up during my testing is that I got an error related to the package version of the Tuva Project. 

An old archived version is hard-coded. It can be updated to `version: [">=0.3.0","<1.0.0"]`

Screenshot 2023-06-07 at 4 53 41 PM

It would be great if you want to include this in your PR; otherwise, I can open a new one. Thanks!

**Comment by msolnit** [comment]
Thanks for getting these over the finish line, @sarah-tuva! I noticed the package version issue as well, and would have eventually gotten around to submitting a PR for it, but I'm happy to let you take the lead :-).

**Pull request merged**
